### ISSUE TITLE
Relax distributed version constraint

### ISSUE THREAD

**Issue by mrocklin** [PrefectHQ/prefect-dask#115]
I notice that this package is currently pinned below `<=2023.3.1`.  

Is there anything we can do on the Dask side here to unblock this?

**Comment by jrbourbeau** [comment]
I think @zanieb and I chatted about this over in https://github.com/PrefectHQ/prefect-dask/pull/103. @zanieb maybe the upper bound can already be removed?

**Comment by zanieb** [comment]
Hm yeah it seems like we lost track of this while waiting for that fix to be released. I'm not at Prefect anymore, maybe @serinamarie can look into it.

**Comment by mrocklin** [comment]
It looks like this has been done.  Thanks all. 

I'm curious, when can we release next?  Anything we can do to help with this process?

**Comment by desertaxle** [comment]
@mrocklin we'll cut a new version today that will have the `distributed` upper pin removed.

**Comment by jrbourbeau** [comment]
That's great, thank you @desertaxle

**Comment by mrocklin** [comment]
Oh great.  Thanks all.
