### ISSUE TITLE
How to best use Dask objects in a Prefect task

### ISSUE THREAD

**Issue by scharlottej13** [PrefectHQ/prefect-dask#26]
@khuyentran1401 and I are working together provide updated examples/content using Prefect 2.0 with Dask and Coiled (see https://github.com/coiled/feedback/issues/191).

We've seen a few Coiled users have some trouble when using Dask objects within a Prefect task executed with the `DaskTaskRunner`. The following snippet, for example, results in a `PrefectHTTPStatusError`:

<details><summary>full error</summary>

```python-traceback
"PrefectHTTPStatusError(""Client error '404 Not Found' for url 'http://ephemeral-orion/api/task_runs/154f7c8c-0ec8-478c-824f-100e8905a9ef/set_state'\nResponse: {'exception_message': 'Task run with id 154f7c8c-0ec8-478c-824f-100e8905a9ef not found'}
```
</details>

```python
from prefect import flow, task
from prefect_dask.task_runners import DaskTaskRunner
import dask

coiled_executor = DaskTaskRunner(
    cluster_class="coiled.Cluster",
    cluster_kwargs={
        "n_workers" : 4,
        "shutdown_on_close": True,
        "software": "prefect2-example",
    }
)


@task
def some_data_manipulation():
    df = dask.datasets.timeseries(
        "2000", "2020", partition_freq="2w"
    ).persist()
    df.groupby("name").aggregate({"x": "sum", "y": "max"}).compute()


@flow(task_runner=coiled_executor)
def test_flow():
    some_data_manipulation.submit()


if __name__ == "__main__":	
    test_flow()
```
Running the same example locally with Dask's `LocalCluster` also doesn't work-- I get a number of memory limit warnings, restarted workers, and eventually a `ConnectError`.

Instead, **what works great** is using Prefect's default (not specifying a task runner) for tasks with Dask objects or the `DaskTaskRunner` for task parallelization. Both of these examples work really nicely both locally and with a Coiled cluster:

<details>
<summary>Default task runner code snippet</summary>

```python
import coiled
import dask
from dask.distributed import Client
from prefect import flow, task, get_run_logger


@task
def load_data():
    """Load some data"""
    return dask.datasets.timeseries("2000", "2005", partition_freq="2w").persist()


@task
def summarize(df):
    """Compute a summary table"""
    return df.groupby("name").aggregate({"x": "sum", "y": "max"}).compute()


@task
def log_summary(df):
    """Log summary result"""
    logger = get_run_logger()
    logger.info(df)


@flow
def timeseries_flow():
    df = load_data()
    summary_df = summarize(df)
    log_summary(summary_df)


# will appear in the Prefect 2.0 UI without additional configuration!
with coiled.Cluster(
    name="prefect-example", n_workers=5, sofware='prefect2-example'
) as cluster:
    client = Client(cluster)
    timeseries_flow()
```
</details>

<details>
<summary>DaskTaskRunner code snippet</summary>

```python
from prefect import flow, task
from prefect_dask import DaskTaskRunner


@task
def inc(x):
    return x + 1


@task
def double(x):
    return x * 2


@task
def add(x, y):
    return x + y


@task
def sum_all(z):
    return sum(z)


@flow(task_runner=DaskTaskRunner(
    cluster_class="coiled.Cluster",
    cluster_kwargs={
        "n_workers": 6,
        # Coiled software environment
        "software": "prefect2-example",
        # set shutdown_on_close to False to re use the cluster
        "shutdown_on_close": True,
        # name of the cluster, for easy reference
        "name": "prefect-dask-runner",
    }))
def inc_double_add_sum(a_range):
    a = inc.map(a_range)
    b = double.map(a_range)
    c = add.map(x=a, y=b)
    return sum_all(c)


inc_double_add_sum(range(10))
```
</details>

All examples run using:
- python 3.9
- [coiled-runtime](https://github.com/coiled/coiled-runtime#readme) 0.1.0
- prefect 2.0.0
- prefect_dask 0.1.2

I *think* this is because using the `DaskTaskRunner` for Dask objects is similar to launching a task from within a task, which is generally not recommended, except for specific use cases (see [Dask Distributed docs](https://distributed.dask.org/en/stable/task-launch.html)).

Which leads to my specific question, what is the recommended way for using Prefect with Dask objects?

Thanks in advance for your help!

cc @jrbourbeau @phobson

**Comment by khuyentran1401** [comment]
@scharlottej13 Thanks for opening the issue! @desertaxle, maybe you have some insights into this?

**Comment by ahuang11** [comment]
To clarify, are the users using Prefect Cloud or local Orion?

`"PrefectHTTPStatusError(""Client error '404 Not Found' for url 'http://ephemeral-orion/api/task_runs/154f7c8c-0ec8-478c-824f-100e8905a9ef/set_state'\nResponse: {'exception_message': 'Task run with id 154f7c8c-0ec8-478c-824f-100e8905a9ef not found'}`

Based on this error, I think maybe need to run:
```
prefect orion start
prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api
prefect agent start
```

I was able to run using local dask:
```
from prefect import flow, task
from prefect_dask.task_runners import DaskTaskRunner
import dask

@task
def some_data_manipulation():
    df = dask.datasets.timeseries(
        "2000", "2020", partition_freq="2w"
    )
    df.groupby("name").aggregate({"x": "sum", "y": "max"}).compute()


@flow(task_runner=DaskTaskRunner)
def test_flow():
    some_data_manipulation.submit()


if __name__ == "__main__":	
    test_flow()
```

**Comment by ahuang11** [comment]
In regards to memory issue, I think it's related to:
https://github.com/PrefectHQ/prefect-dask/issues/18

So I think you may need to get a client inside the task:
```
from prefect import flow, task
from prefect_dask.task_runners import DaskTaskRunner
from dask.distributed import get_client
import dask


task_runner = DaskTaskRunner()

@task
def some_data_manipulation():
    client = get_client()
    df = dask.datasets.timeseries(
        "2000", "2020", partition_freq="2w"
    )
    df_agg = df.groupby("name").aggregate({"x": "sum", "y": "max"})
    client.compute(df_agg)

@flow(task_runner=task_runner)
def test_flow():
    some_data_manipulation.submit()


if __name__ == "__main__":	
    test_flow()
```

**Comment by scharlottej13** [comment]
Thank you @ahuang11 for your help! I appreciate you splitting up these issues. I'll do the same below in two separate comments.

Regarding passing `coiled.cluster` to `DaskTaskRunner`, I tried this again, but with the much simpler example from the Prefect docs so as not to conflate the two issues.

Trying this example:
```python
import time
from prefect import flow, task
from prefect_dask.task_runners import DaskTaskRunner

# running on Coiled
coiled_executor = DaskTaskRunner(
	cluster_class="coiled.Cluster",
	cluster_kwargs={
		"n_workers" : 2,
		"software": "prefect2-example",
	},
)

@task
def shout(number):
    time.sleep(0.5)
    print(f"#{number}")

@flow(task_runner=coiled_executor)
def count_to(highest_number):
    for number in range(highest_number):
        shout.submit(number)


if __name__ == "__main__":	
	count_to(10)
```

using Prefect Orion with:
```
prefect orion start
prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api
```
I get `RuntimeError: Cannot orchestrate task run '8ca46f85-410b-471b-bc5b-d1b5a1a6f4ea'. Failed to connect to API at http://127.0.0.1:4200/api/.`

If instead, I use Prefect Cloud by doing:
```
prefect cloud workspace set --workspace "scharlottej13githubexamplecom/sarah-coiled"
prefect cloud login -k <my-key>
```
The flow runs successfully without error.

Is it expected that using Prefect Orion locally would have trouble scheduling tasks on a remote cluster? On a high-level that makes sense, but I didn't see anything in the docs to this point.

**Comment by scharlottej13** [comment]
In regards to the best way to use Dask with Prefect, I agree the memory error is related to #18. I also found an older issue for Prefect 1.0 that seems related https://github.com/PrefectHQ/prefect/discussions/3022 and suggests a similar workaround.

When I get a client from within a task as you suggested, I no longer see the memory errors. My follow-up question, which may require some additional investigation, is whether this is preferred to using the `ConcurrentTaskRunner`, especially given that launching a task from a task in Dask is not generally recommended. Instead, maybe it makes more sense to steer those using Dask objects to something like:

```python
import dask
from dask.distributed import LocalCluster, Client
from prefect import flow, task, get_run_logger


@task
def some_data_manipulation():
    df = dask.datasets.timeseries(
        "2000", "2020", partition_freq="2w"
    ).persist()
    df_agg = df.groupby("name").aggregate({"x": "sum", "y": "max"}).compute()

@flow
def timeseries_flow():
    df = load_data()

with LocalCluster() as cluster:
    client = Client(cluster)
    timeseries_flow()
```

What do you think?

**Comment by ahuang11** [comment]
For the first point, are you able to run with the local orion server (without coiled)? e.g.

```
import time
from prefect import flow, task
from prefect_dask.task_runners import DaskTaskRunner

# running on Coiled
coiled_executor = DaskTaskRunner()

@task
def shout(number):
    time.sleep(0.5)
    print(f"#{number}")

@flow(task_runner=coiled_executor)
def count_to(highest_number):
    for number in range(highest_number):
        shout.submit(number)


if __name__ == "__main__":
    count_to(10)
```

**Comment by ahuang11** [comment]
In regards to the second point, I think it does require some investigation, and perhaps some changes to the internal code of prefect-dask to check `is_dask_collection`

**Comment by ahuang11** [comment]
In regards to the second point, I think it does require some investigation, and perhaps some changes to the internal code of prefect-dask to check `is_dask_collection`

**Comment by scharlottej13** [comment]
> For the first point, are you able to run with the local orion server (without coiled)? e.g.

Yes! Running Dask locally with the `DaskTaskRunner` works just fine with Orion or Cloud.

> Perhaps also peek at how Prefect 1 `LocalDaskExecutor` operated as well (whether it could resolve dask collections within task without calling client).

That makes sense. Based on the discussion in https://github.com/PrefectHQ/prefect/discussions/3022 my guess is this was still the case in Prefect 1.0, but would be good to take a look.

@ahuang11 feel free to let me know if you need any help from folks on the Dask side for these next steps.

**Comment by ahuang11** [comment]
Thanks for the support! Quick question, is there a way to get an account on Coiled? Do I simply sign up or is there a way to provide a testing account for us? Haven't really taken a deep look at it.

**Comment by scharlottej13** [comment]
> Thanks for the support! Quick question, is there a way to get an account on Coiled? Do I simply sign up or is there a way to provide a testing account for us? Haven't really taken a deep look at it.

Yes! It's free to [sign up](https://cloud.coiled.io/signup) and you'll get enough more than enough free credits to start to test all of these things. You'll need an existing AWS or Google Cloud account. Feel free to ping me on the Prefect slack if you have questions!

**Comment by ahuang11** [comment]
Michael answered "Is it expected that using Prefect Orion locally would have trouble scheduling tasks on a remote cluster? On a high-level that makes sense, but I didn't see anything in the docs to this point." here:
https://github.com/PrefectHQ/prefect/issues/6812#issuecomment-1247012640

**Comment by scharlottej13** [comment]
@ahuang11 I just realized in my initial question I mistakenly assumed the `ConcurrentTaskRunner` was the default. I've edited my question to reflect that I was not specifying any task runner when working with Dask objects. I don't think this changes the nature of our discussion, apologies if this caused any confusion.

**Comment by ahuang11** [comment]
I think it defaults to ConcurrentTaskRunner if you call the `submit` method on a task.

**Comment by scharlottej13** [comment]
> I think it defaults to ConcurrentTaskRunner if you call the `submit` method on a task.

That is also my understanding, however, I did not call `submit`:

```python
import coiled
import dask
from dask.distributed import Client
from prefect import flow, task, get_run_logger


@task
def load_data():
    """Load some data"""
    return dask.datasets.timeseries("2000", "2005", partition_freq="2w").persist()


@task
def summarize(df):
    """Compute a summary table"""
    return df.groupby("name").aggregate({"x": "sum", "y": "max"}).compute()


@task
def log_summary(df):
    """Log summary result"""
    logger = get_run_logger()
    logger.info(df)


@flow
def timeseries_flow():
    df = load_data()
    summary_df = summarize(df)
    log_summary(summary_df)


# will appear in the Prefect 2.0 UI without additional configuration!
with coiled.Cluster(
    name="prefect-example", n_workers=5, sofware='prefect2-example'
) as cluster:
    client = Client(cluster)
    timeseries_flow()
```

**Comment by scharlottej13** [comment]
@ahuang11 I've had some time to test out using `dask.distributed.get_client` within a Prefect task. This works locally with Dask's `LocalCluster`, but when using Coiled, you instead need to create a new cluster object within the task by referring to the original cluster name:

```python
import coiled
import dask
from dask.distributed import Client
from prefect import flow, task
from prefect_dask import DaskTaskRunner

coiled_runner = DaskTaskRunner(
    cluster_class="coiled.Cluster",
    cluster_kwargs={
        "n_workers": 5,
        "software": "prefect2-example",
        "name": "prefect-dask-runner",
    },
)


@task
def calling_compute_in_a_task():
    cluster = coiled.Cluster(name="prefect-dask-runner")
    client = Client(cluster)
    df = dask.datasets.timeseries("2000", "2005", partition_freq="2w")
    summary_df = df.describe()
    client.compute(summary_df)


@flow
def test_flow(task_runner=coiled_runner):
    describe_df = calling_compute_in_a_task.submit()


if __name__ == "__main__":
    test_flow()
```

This could cause other problems down the line, though. On the Prefect side, I'm not sure if Prefect would think it is the sole owner of the cluster. We'd probably still steer folks away from this option, pending any advice from you or other folks at Prefect who may have a better understanding on this.

**Comment by madkinsz** [comment]
I believe you should be able to get a client from the worker with `worker_client`. https://distributed.dask.org/en/stable/api.html#distributed.worker_client

**Comment by madkinsz** [comment]
Interesting! Thanks for trying it out. It seems like Coiled cluster workers should support this. Does it work when submitting a function directly to the Coiled cluster (i.e. without a Prefect task)? Can you check in with the `distributed` team if this is expected?

**Comment by scharlottej13** [comment]
> Interesting! Thanks for trying it out. It seems like Coiled cluster workers should support this. Does it work when submitting a function directly to the Coiled cluster (i.e. without a Prefect task)?

@madkinsz of course, thanks for the help. Using `dask.distributed.worker_client` does work on a Coiled cluster without Prefect:
```python
import coiled
from dask.distributed import worker_client, Client


def fib(n):
    if n < 2:
        return n
    with worker_client() as client:
        a_future = client.submit(fib, n - 1)
        b_future = client.submit(fib, n - 2)
        a, b = client.gather([a_future, b_future])
    return a + b


if __name__ == "__main__":
    cluster = coiled.Cluster(name="test-worker-client", package_sync=True)
    client = Client()
    future = client.submit(fib, 10)
    result = future.result()
    print(result)  # prints "55"
```

**Comment by madkinsz** [comment]
Does it work when using a cluster with the `asynchronous=True` flag or submitting an asynchronous function? We also run synchronous user tasks in a worker thread, perhaps that's interfering with lookup of the "global" client?

**Comment by ahuang11** [comment]
> 

I noticed that `task_runner` was passed to the flow's function keyword argument rather than the `flow` decorator.

Using:
```
import dask
from dask.distributed import worker_client
from prefect import flow, task
from prefect_dask import DaskTaskRunner

task_runner = DaskTaskRunner()


@task
def calling_compute_in_a_task():
    with worker_client() as client:
        df = dask.datasets.timeseries("2000", "2005", partition_freq="2w")
        summary_df = df.describe()
        client.compute(summary_df)


@flow(task_runner=task_runner)
def test_flow():
    calling_compute_in_a_task.submit()


if __name__ == "__main__":
    test_flow()
```

I get:
```


File ~/mambaforge/envs/prefect-dask/lib/python3.9/site-packages/distributed/worker_client.py:57, in worker_client()
     55 client = get_client(timeout=timeout)
     56 if separate_thread:
---> 57     duration = time() - thread_state.start_time
     58     secede()  # have this thread secede from the thread pool
     59     worker.loop.add_callback(
     60         worker.handle_stimulus,
     61         SecedeEvent(
   (...)
     65         ),
     66     )

AttributeError: '_thread._local' object has no attribute 'start_time'
```


However, if I specify `separate_thread=False` it works:
```
import dask
from dask.distributed import worker_client
from prefect import flow, task
from prefect_dask import DaskTaskRunner

task_runner = DaskTaskRunner()


@task
def calling_compute_in_a_task():
    with worker_client(separate_thread=False) as client:
        df = dask.datasets.timeseries("2000", "2005", partition_freq="2w")
        summary_df = df.describe()
        client.compute(summary_df)


@flow(task_runner=task_runner)
def test_flow():
    calling_compute_in_a_task.submit()


if __name__ == "__main__":
    test_flow()
```

**Comment by madkinsz** [comment]
I think including a `get_dask_client` utility in this repository that manages the proper invocation seems helpful

**Comment by ahuang11** [comment]
Can you clarify on `get_dask_client`?

Do you mean as a keyword argument to `DaskTaskRunner(get_dask_client=True)`?

Or like as a statement inside the task?
```
@task
def test_task():
    with get_dask_client() as client:
```

If the latter, is the only difference between `get_dask_client` and `worker_client` is set `separate_thread=False`?

**Comment by madkinsz** [comment]
`DaskTaskRunner.submit` shouldn't wrap all tasks with a worker client context. Retrieving a worker client has performance implications — I believe it secedes the task from the worker’s thread pool. It's also not clear how we'd get it to the user.

Instead, I think we should document our required pattern for accessing the client. If we want, we can add a utility to the library that, as you noted, just sets the required keyword argument. The utility function is nice because:
- We can maintain it over time without our users having to change their invocations 
- It is discoverable without reading documentation — otherwise I'd never guess that I need to pass `separate_thread`
- We can account for both sync and async invocations

**Comment by ahuang11** [comment]
That sounds good to me.

@scharlottej13 would you be able to test if this snippet works on Coiled?
```
import dask
from dask.distributed import worker_client
from prefect import flow, task
from prefect_dask import DaskTaskRunner

coiled_runner = DaskTaskRunner(
    cluster_class="coiled.Cluster",
    cluster_kwargs={
        "n_workers": 5,
        "software": "prefect2-example",
        "name": "prefect-dask-runner",
    },
)


@task
def calling_compute_in_a_task():
    with worker_client(separate_thread=False) as client:
        df = dask.datasets.timeseries("2000", "2005", partition_freq="2w")
        summary_df = df.describe()
        client.compute(summary_df)


@flow(task_runner=coiled_runner)
def test_flow():
    calling_compute_in_a_task.submit()


if __name__ == "__main__":
    test_flow()
```

**Comment by scharlottej13** [comment]
@ahuang11 yup that works on Coiled!

**Comment by ahuang11** [comment]
Thanks! I'll add that utility

**Comment by BadAsstronaut** [comment]
This approach also works using the `dask_cloudprovider.aws.FargateCluster` package. Thanks so much!

**Comment by ahuang11** [comment]
I created a PR; feel free to test and/or leave suggestions there!
https://github.com/PrefectHQ/prefect-dask/pull/33

**Comment by ahuang11** [comment]
This is now released!
https://prefecthq.github.io/prefect-dask/#distributing-dask-collections-across-workers
