### ISSUE TITLE
Dask task names do not match Prefect task names

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect-dask#27]
In Prefect 1.0 (see https://github.com/PrefectHQ/prefect/pull/2814), the task names that appear in the Dask dashboard match the Prefect task names. This is no longer the case in 2.0 which makes it a lot harder to diagnose issues. 
Example:
```
N = 100

@task(name="f")
def f(x):
    time.sleep(1)
    return 2 * x

def main():
    start = time.time()
    tasks = f.map(range(N))
    submitted = time.time()
    return sum([t.result() for t in tasks])

flow(task_runner=DaskTaskRunner("localhost:8786"))(main)()
```
Result: tasks all have random UUID-ish names
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/903655/189979089-24e8e27c-9050-4af6-beeb-129950d8b9af.png">

**Comment by madkinsz** [comment]
This was broken in the latest update of #21
