### ISSUE TITLE
Tasks stuck in running indefinitely

### ISSUE THREAD

**Issue by BitTheByte** [PrefectHQ/prefect-dask#59]
For some reason - it might be race condition - tasks are stuck in a running state. As shown in dask dashboard there are no tasks to process. however, prefect thinks that there are tasks still being in a "running" state and thus still waiting for them to complete causing the flow to hang indefinitely.

This behavior is caused randomly however it has a higher chance to happen when the adaptive mode is enabled with a relatively large changing number of workers e.g. `1-50` which made me believe this is caused due to dask moving tasks around.

Feel free to revise cloud logs at: https://app.prefect.cloud/account/a5aa4a76-f2a5-4e07-bb53-f0e7ff684f5b/workspace/f480ae44-ee5d-467a-ba06-85a65419eb76/flow-runs/flow-run/5cb4bc51-3746-4a04-8e63-d9f45b25dbd4

I also noticed that sometimes when a dask worker is killed and tasks get resubmitted the total number of tasks doesn't change however the completed ones do to be more clear
```
Task Flow                                                 | Finished
---------------------------------------------------------------------
T1, T2 -> Submitted                                             [0/2]
T1 -> Running -> Finished -> [ State saved on worker 1]         [1/2]
T2 -> Submitted -> Running -> Worker 1 Killed                   [1/2]

.... Worker Start
T1 -> Resubmiited -> Running -> [Prefect Return Old State]      [2/2]

T2 Lost in running state????
```

![image](https://user-images.githubusercontent.com/16452985/209011268-f45c1ace-f3cf-4b3f-9ebc-7ccd26d94bb7.png)

![image](https://user-images.githubusercontent.com/16452985/209011621-67d6e6e5-80a0-4a3c-9aba-6682f399b6f9.png)

**Comment by ahuang11** [comment]
Thanks for reporting. Would you be able to share a minimal example so I can try reproducing?

**Comment by BitTheByte** [comment]
Hello @ahuang11 

Any simple workflow using prefect-dask and dask-kubernetes with adaptive mode will do

**Comment by BitTheByte** [comment]
@ahuang11 

Do we have an update on this issue?

**Comment by madkinsz** [comment]
Hi @BitTheByte please do not ask for updates on issues — we will add content to the issue when we have more information.

If you want to help, it looks like the next step is to write a simple minimal reproduction script so we can observe the issue.

**Comment by BitTheByte** [comment]
This does seem to be more related to Dask rather than Prefect. closing until further notice
