### ISSUE TITLE
Code snippets in README markdown not displaying properly

### ISSUE THREAD

**Issue by the-matt-morris** [PrefectHQ/prefect-dask#60]
These lines:

https://github.com/PrefectHQ/prefect-dask/blob/d93af77096d596ad9b254b1a6527913b36f04b63/README.md?plain=1#L152-L168

render as such in the README:

![image](https://user-images.githubusercontent.com/102183561/209858696-86928ea1-8aa3-487a-a37f-b21f5a0dc35e.png)

Will need to reformat the markdown.  I can submit a PR, just lemme know.  Thanks!

**Comment by ahuang11** [comment]
Thanks; initially I optimized for docs, but README is important too! I'd appreciate it if you can help submit a PR!

**Comment by the-matt-morris** [comment]
Ah yeah, that makes sense.  Docs look great!  I'll submit a PR on the README

**Comment by ahuang11** [comment]
I should clarify that they're linked, `mkdocs serve` copies the README file, but I don't mind that the warning annotation is removed.

**Comment by the-matt-morris** [comment]
Hmm...I can run mkdocs locally to preview and make sure everything looks ok.  I wouldn't want to mess up the docs, but perhaps this isn't possible to render these warning boxes appropriately in markdown, but I'll play around with it
